spring:
  application:
    name: numbers-service

server:
  port: 0

security:
  basic:
    enabled: false

logging:
  level:
    ROOT: INFO
    org.springframework.cloud: DEBUG
    io.pivotal.springcloud: DEBUG
