spring:
  application:
    name: ${vcap.application.name:numbers-service}

security:
  basic:
    enabled: false

logging:
  level:
    ROOT: INFO
    org.springframework.cloud: DEBUG
    io.pivotal.springcloud: DEBUG
