spring:
  application:
    name: numbers-service

server:
  port: 0

security:
  basic:
    enabled: false

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
